spring.application.name=config-service


# Server Port
server.port=9092

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fetch registry every 30 seconds
eureka.client.registry-fetch-interval-seconds=30

# Heartbeat every 5 seconds
eureka.instance.lease-renewal-interval-in-seconds=5

# Expire instance after 10 seconds if no heartbeat
eureka.instance.lease-expiration-duration-in-seconds=10

# Config Server Git Repo
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/MO20564975/Desktop/practice_project_one/config-repo

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
